public class Card {

//    HAS A STRING SUIT.. USE THE UNICODE CHARACTERS OF HEART, CLUB, DIAMOND AND SPADE

//    HAS A STRING SYMBOL (2,3,4,5,6,7,8,9,10,J,Q,K,A)

//    HAS AN INT VALUE (2,3,4,5,6,7,8,9,10,11)

//    HAS A toString METHOD THAT DESCRIBES THE CLASS



}
