public class CardGame {

//    USING CLASSES, ARRAY LISTS AND METHODS, CREATE A DECK OF CARDS. YOU SHOULD USE THE FOLLOWING CLASSES
//    CARD GAME




//    CONTAINS AN ARRAYLIST<CARD> FOR THE DECK OF CARDS THAT CONTAINS ALL 52 CARDS.
//    THIS IS CREATED AND POPULATED WHEN THE GAME IS CONSTRUCTED

//    HAS A NAME WHICH IS ALSO DEFINED IN THE CONSTRUCTOR

//    HAS A GET DECK METHOD THAT LISTS OUT THE CARDS IN THE DECK
}
